import ROOT
import sys
import subprocess
import string,math,os
import ConfigParser
import glob
import numpy as np
inFileName = sys.argv [1]
samp_mass = sys.argv [2]
label = sys.argv [3]

print (" Reading from "+ inFileName + "Mass point is "+ samp_mass)
inFile = ROOT.TFile.Open(inFileName ,"READ") 
c = ROOT.TCanvas("c","c",600,600)      
c.SetBorderSize(0)   
c.SetFrameBorderMode(0)
ROOT.gROOT.SetBatch(True)
ROOT.gStyle.SetTitleBorderSize(0)
ROOT.gStyle.SetOptStat(0)

#ROOT.TColor.Colorpalettes(195)
#ROOT.gStyle.SetPalette(156)
#inFile.cd('simple')

outfolder = ('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label)
def checkAndMakeDir(dir):
    if not os.path.exists(dir):
        os.mkdir(dir)

def clearDir(dir):
    for fil in glob.glob(dir+"/*"):
        os.remove(fil)
        
def Make_Geo(Unmatched_Hist_Name, Mass, canvas, inFi, outDir):
    Close_Plot=inFi.Get("simple/"+Unmatched_Hist_Name)
    Close_Plot.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle()+" || "+ Mass)
    Close_Plot.SetAxisRange(0., 1.,"Y")
    Close_Plot.SetAxisRange(0., 1.,"X")
    Close_Plot.GetXaxis().SetTitle("dR(tau, e)")
    Close_Plot.GetYaxis().SetTitle("dR(e,jet)")
    Close_Plot.Draw("COL Z CJUST")
    canvas.SaveAs(outDir+"0to1_"+Unmatched_Hist_Name+".png")
    canvas.Clear()
    Full_Plot=inFi.Get("simple/"+Unmatched_Hist_Name)
    ETau=Full_Plot.ProjectionX()
    ETau.SetAxisRange(0., 1.,"X")
    ETau.SetTitle(Full_Plot.GetTitle().replace("dR (Ele,Tau) Vs dR(Jet,Ele)", "Delta R(e,tau)"))
    ETau.Draw()
    canvas.SaveAs(outDir+"FULL_TH1_"+Unmatched_Hist_Name+".png")
    canvas.Clear()

    Full_Plot.Rebin2D(3,3)
    Full_Plot.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle()+" || "+ Mass)
    Full_Plot.GetXaxis().SetTitle("dR(tau, e)")
    Full_Plot.GetYaxis().SetTitle("dR(e, jet)")
    Full_Plot.Draw("COL Z CJUST")
    canvas.SaveAs(outDir+"FULL_"+Unmatched_Hist_Name+".png")
    canvas.Clear()
    ETau=Close_Plot.ProjectionX()
    ETau.SetTitle(Close_Plot.GetTitle().replace("dR (Ele,Tau) Vs dR(Jet,Ele)", "Delta R(e,tau)"))
    ETau.Draw()
    canvas.SaveAs(outDir+"0to1_TH1_"+Unmatched_Hist_Name+".png")
    canvas.Clear()

def Make_MET_Jet(Unmatched_Hist_Name, Mass, canvas, inFi, outDir):
    Hist=inFi.Get("simple/"+Unmatched_Hist_Name)
    Hist.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle()+" || "+ Mass)
    Hist.Rebin2D(1,3)

    Hist.GetXaxis().SetTitle("dPhi (MET,Jet)")
    Hist.GetYaxis().SetTitle("Met GEV")
    Hist.Draw("COL Z CJUST")
    canvas.SaveAs(outDir+Unmatched_Hist_Name+".png")
    Projection=Hist.ProjectionY()
    Projection.SetTitle(Hist.GetTitle().replace("dPhi (MET,Jet) Vs Met", "MET"))
    Projection.Draw()
    canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("MET_VS_JdPhiM","MET")+".png")
    canvas.Clear()
    Projection=Hist.ProjectionX()
    Projection.SetTitle(Hist.GetTitle().replace("dPhi (MET,Jet) Vs Met", "dPhi (MET,Jet)"))
    Projection.Draw()
    canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("MET_VS_JdPhiM","JdPhiM")+".png")
    canvas.Clear()

def Make_MVis(Unmatched_Hist_Name, Mass, canvas, inFi, outDir, gen):
    Hist=inFi.Get("simple/"+Unmatched_Hist_Name).ProjectionY()
    Hist.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle())
    if (Mass=="M10" or Mass=="m10"):
        Hist.SetAxisRange(0., 10.,"X")
    else:
        Hist.RebinX(2)
    Hist.Draw()
    canvas.SaveAs(outDir+""+Unmatched_Hist_Name+".png")
    canvas.Clear()
    if not gen:
        Hist_f=inFi.Get("simple/"+Unmatched_Hist_Name+"_f").ProjectionY()
        Hist_f.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_f").GetTitle())
        if (Mass=="M10" or Mass=="m10"):
            Hist_f.SetAxisRange(0., 10.,"X")
        else:
            Hist_f.RebinX(2)
        Hist_f.Draw()
        canvas.SaveAs(outDir+""+Unmatched_Hist_Name+"_f"+".png")
        canvas.Clear()
        Hist_m=inFi.Get("simple/"+Unmatched_Hist_Name+"_m").ProjectionY()
        Hist_m.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_m").GetTitle())
        if (Mass=="M10" or Mass=="m10"):
            Hist_m.SetAxisRange(0., 10.,"X")
        else:
            Hist_m.RebinX(2)
        Hist_m.Draw()
        canvas.SaveAs(outDir+""+Unmatched_Hist_Name+"_m"+".png")
        canvas.Clear()
        StackedHist = ROOT.THStack("hs", Hist_m.GetTitle().replace("Matched", "Stacked"))
        Hist_f.SetLineColor(ROOT.kBlue)
        StackedHist.Add(Hist_f)
        Hist_m.SetLineColor(ROOT.kGreen)
        StackedHist.Add(Hist_m)
        StackedHist.Draw("BAR1")
        leg = ROOT.TLegend(.73,.32,.97,.41)
        leg.SetBorderSize(0)
        leg.SetFillColor(0)
        leg.SetFillStyle(0)
        leg.SetTextFont(42)
        leg.SetTextSize(0.035)
        leg.AddEntry(Hist_m,"Matched","f")
        leg.AddEntry(Hist_f,"Fake","f")

        leg.Draw()
        canvas.SaveAs(outDir+""+Unmatched_Hist_Name+"_Stacked"+".png")    
        c.Clear()

def Make_IDPT(Unmatched_Hist_Name, Mass, canvas, inFi, outDir, isMVA, gen):
    Hist=inFi.Get("simple/"+Unmatched_Hist_Name)
    Hist.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle().replace("IDVs Pt", "Electron MVA ID vs. Electron PT")+" || "+ Mass)
    Hist.GetXaxis().SetTitle("MVA ID")
    Hist.GetYaxis().SetTitle("Electron PT")
    Hist.Draw("COL Z CJUST")
    canvas.SaveAs(outDir+Unmatched_Hist_Name+".png")
    ProjectionY=Hist.ProjectionY()
    ProjectionY.SetTitle(Hist.GetTitle().replace("MVA ID Val vs. Pt", "Electron PT"))
    ProjectionY.Draw()
    canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","ElePT")+".png")
    canvas.Clear()
    if isMVA:
        ProjectionX=Hist.ProjectionX()
        ProjectionX.SetTitle(Hist.GetTitle().replace("MVA ID Val vs. Pt", "MVA ID Val"))
        ProjectionX.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","MVA_ID")+".png")
        canvas.Clear()
    if not gen:
        Hist_f=inFi.Get("simple/"+Unmatched_Hist_Name+"_f")
        Hist_f.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_f").GetTitle())
        ProjectionY_f=Hist_f.ProjectionY()
        ProjectionY_f.SetTitle(Hist_f.GetTitle().replace("MVA ID Val vs. Pt", "Electron PT"))
        ProjectionY_f.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","ElePT")+"_f.png")
        canvas.Clear()
        if isMVA:
            ProjectionX_f=Hist_f.ProjectionX()
            ProjectionX_f.SetTitle(Hist_f.GetTitle().replace("MVA ID Val vs. Pt", "MVA ID Val"))
            ProjectionX_f.Draw()
            canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","MVA_ID")+"_f.png")
            canvas.Clear()
        Hist_m=inFi.Get("simple/"+Unmatched_Hist_Name+"_m")
        Hist_m.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_m").GetTitle())
        ProjectionY_m=Hist_m.ProjectionY()
        ProjectionY_m.SetTitle(Hist_m.GetTitle().replace("MVA ID Val vs. Pt", "Electron PT"))
        ProjectionY_m.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","ElePT")+"_m.png")
        canvas.Clear()
        if isMVA:
            ProjectionX_m=Hist_m.ProjectionX()
            ProjectionX_m.SetTitle(Hist_m.GetTitle().replace("MVA ID Val vs. Pt", "MVA ID Val"))
            ProjectionX_m.Draw()
            canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("ID_PT","MVA_ID")+"_m.png")
            canvas.Clear()
            StackedHist = ROOT.THStack("hs", ProjectionX_m.GetTitle().replace("Matched", "Stacked"))
            ProjectionX_f.SetLineColor(ROOT.kBlue)
            StackedHist.Add(ProjectionX_f)
            ProjectionX_m.SetLineColor(ROOT.kGreen)
            StackedHist.Add(ProjectionX_m)
            StackedHist.Draw()
            leg = ROOT.TLegend(.73,.32,.97,.41)
            leg.SetBorderSize(0)
            leg.SetFillColor(0)
            leg.SetFillStyle(0)
            leg.SetTextFont(42)
            leg.SetTextSize(0.035)
            leg.AddEntry(ProjectionX_m,"Matched","f")
            leg.AddEntry(ProjectionX_f,"Fake","f")

            leg.Draw()
            canvas.SaveAs(outDir+Unmatched_Hist_Name.replace("ID_PT","MVA_ID")+"_Stacked.png")    
            c.Clear()
        StackedHist = ROOT.THStack("hs", ProjectionY_m.GetTitle().replace("Matched", "Stacked"))
        ProjectionY_f.SetLineColor(ROOT.kBlue)
        StackedHist.Add(ProjectionY_f)
        ProjectionY_m.SetLineColor(ROOT.kGreen)
        StackedHist.Add(ProjectionY_m)
        StackedHist.Draw()
        leg = ROOT.TLegend(.73,.32,.97,.41)
        leg.SetBorderSize(0)
        leg.SetFillColor(0)
        leg.SetFillStyle(0)
        leg.SetTextFont(42)
        leg.SetTextSize(0.035)
        leg.AddEntry(ProjectionY_m,"Matched","f")
        leg.AddEntry(ProjectionY_f,"Fake","f")

        leg.Draw()
        canvas.SaveAs(outDir+Unmatched_Hist_Name.replace("ID_PT","PT_ID")+"_Stacked.png")    
        c.Clear()


def Make_TauGeo(Unmatched_Hist_Name, Mass, canvas, inFi, outDir, gen):
    Hist=inFi.Get("simple/"+Unmatched_Hist_Name)
    Hist.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name).GetTitle().replace("IDVs Pt", "Electron MVA ID vs. Electron PT")+" || "+ Mass)
    Hist.GetXaxis().SetTitle("DeltaPhi(MET,Tau)")
    Hist.GetYaxis().SetTitle("DeltaR(Jet,Tau)")
    Hist.Draw("COL Z CJUST")
    canvas.SaveAs(outDir+Unmatched_Hist_Name+".png")
    ProjectionY=Hist.ProjectionY()
    ProjectionY.SetTitle(Hist.GetTitle().replace("dPhi (MET,Tau) Vs ", ""))
    ProjectionY.Draw()
    canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("METtoTau_","")+".png")
    canvas.Clear()
    ProjectionX=Hist.ProjectionX()
    ProjectionX.SetTitle(Hist.GetTitle().replace(" Vs Dr(Jet,Tau) ", ""))
    ProjectionX.Draw()
    canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("JettoTau_","")+".png")
    canvas.Clear()
    if not gen:
        Hist_f=inFi.Get("simple/"+Unmatched_Hist_Name+"_f")
        Hist_f.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_f").GetTitle())
        ProjectionY_f=Hist_f.ProjectionY()
        ProjectionY_f.SetTitle(Hist_f.GetTitle().replace("dPhi (MET,Tau) Vs ", ""))
        ProjectionY_f.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("METtoTau_","")+"_f.png")
        canvas.Clear()
        ProjectionX_f=Hist_f.ProjectionX()
        ProjectionX_f.SetTitle(Hist_f.GetTitle().replace(" Vs Dr(Jet,Tau) ", ""))
        ProjectionX_f.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("JettoTau_","")+"_f.png")
        canvas.Clear()
        Hist_m=inFi.Get("simple/"+Unmatched_Hist_Name+"_m")
        Hist_m.SetTitle(inFi.Get("simple/"+Unmatched_Hist_Name+"_m").GetTitle())
        ProjectionY_m=Hist_m.ProjectionY()
        ProjectionY_m.SetTitle(Hist_m.GetTitle().replace("dPhi (MET,Tau) Vs ", ""))
        ProjectionY_m.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("METtoTau_","")+"_m.png")
        canvas.Clear()
        ProjectionX_m=Hist_m.ProjectionX()
        ProjectionX_m.SetTitle(Hist_m.GetTitle().replace(" Vs Dr(Jet,Tau) ", ""))
        ProjectionX_m.Draw()
        canvas.SaveAs(outDir+"TH1_"+Unmatched_Hist_Name.replace("JettoTau_","")+"_f.png")
        canvas.Clear()
        StackedHist = ROOT.THStack("hs", ProjectionX_m.GetTitle().replace("Matched", "Stacked"))
        ProjectionX_f.SetLineColor(ROOT.kBlue)
        StackedHist.Add(ProjectionX_f)
        ProjectionX_m.SetLineColor(ROOT.kGreen)
        StackedHist.Add(ProjectionX_m)
        StackedHist.Draw()
        leg = ROOT.TLegend(.73,.32,.97,.41)
        leg.SetBorderSize(0)
        leg.SetFillColor(0)
        leg.SetFillStyle(0)
        leg.SetTextFont(42)
        leg.SetTextSize(0.035)
        leg.AddEntry(ProjectionX_m,"Matched","f")
        leg.AddEntry(ProjectionX_f,"Fake","f")

        leg.Draw()
        canvas.SaveAs(outDir+Unmatched_Hist_Name.replace("METtoTau_","")+"_Stacked.png")    
        c.Clear()
        StackedHist = ROOT.THStack("hs", ProjectionY_m.GetTitle().replace("Matched", "Stacked"))
        ProjectionY_f.SetLineColor(ROOT.kBlue)
        StackedHist.Add(ProjectionY_f)
        ProjectionY_m.SetLineColor(ROOT.kGreen)
        StackedHist.Add(ProjectionY_m)
        StackedHist.Draw()
        leg = ROOT.TLegend(.73,.32,.97,.41)
        leg.SetBorderSize(0)
        leg.SetFillColor(0)
        leg.SetFillStyle(0)
        leg.SetTextFont(42)
        leg.SetTextSize(0.035)
        leg.AddEntry(ProjectionY_m,"Matched","f")
        leg.AddEntry(ProjectionY_f,"Fake","f")

        leg.Draw()
        canvas.SaveAs(outDir+Unmatched_Hist_Name.replace("JettoTau_","")+"_Stacked.png")    
        c.Clear()

def Make_PT_Overlays(Unmatched_Hist_Name, Mass, canvas, inFi, outDir):
                                                
    NoID_Pt= inFi.Get('simple/'+Unmatched_Hist_Name.replace("REMPLACEME","NoID")).ProjectionY()
    NoID_Pt.SetTitle(NoID_Pt.GetTitle().replace("EHad MVA ID Val vs. Pt", "EHad PT").replace("NoID","")+"("+samp_mass+")")
    NoID_Pt.SetLineColor(ROOT.kBlack)
    NoID_Pt.Draw()
    Loose_Pt= inFile.Get('simple/'+Unmatched_Hist_Name.replace("REMPLACEME","Loose")).ProjectionY()
    Loose_Pt.SetLineColor(ROOT.kRed)
    Loose_Pt.Draw("SAME")
    Medium_Pt= inFile.Get('simple/'+Unmatched_Hist_Name.replace("REMPLACEME","Medium")).ProjectionY()
    Medium_Pt.SetLineColor(ROOT.kCyan)
    Medium_Pt.Draw("SAME")
    Tight_Pt= inFile.Get('simple/'+Unmatched_Hist_Name.replace("REMPLACEME","NoID")).ProjectionY()
    Tight_Pt.SetLineColor(ROOT.kGreen)
    Tight_Pt.Draw("SAME")
    leg = ROOT.TLegend(.73,.32,.97,.53)
    leg.SetBorderSize(0)
    leg.SetFillColor(0)
    leg.SetFillStyle(0)
    leg.SetTextFont(42)
    leg.SetTextSize(0.035)
    if "MVA" in Unmatched_Hist_Name: 
        leg.AddEntry(NoID_Pt,"ID>0","L")
        leg.AddEntry(Loose_Pt,"ID>2","L")
        leg.AddEntry(Medium_Pt,"ID>4","L")
        leg.AddEntry(Tight_Pt,"ID>6","L")
    else:
        leg.AddEntry(NoID_Pt,"NoID","L")
        leg.AddEntry(Loose_Pt,"Loose","L")
        leg.AddEntry(Medium_Pt,"Medium","L")
        leg.AddEntry(Tight_Pt,"Tight","L")
    leg.Draw()
    c.SaveAs(outDir+Unmatched_Hist_Name.replace("ID_","").replace("REPLACEME","Overlayed")+".png")
    ROOT.gPad.SetLogy()
    c.SaveAs(outDir+Unmatched_Hist_Name.replace("ID_","").replace("REPLACEME","Overlayed_LogY")+".png")

    c.Clear()



checkAndMakeDir('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/')
Geometry_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/Geometry_BestPair/'
MET_PreGeo_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MET_PreGeo/'
MET_PostGeo_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MET_PostGeo/'
PT_Stacks_Dir = '/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MET_PostGeo/'
ID_PT_PreGeo_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/ID_PT_BestPair_PreGeo/'
ID_PT_PostGeo_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/ID_PT_BestPair_PostGeo/'
Mvis_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MVis_BestPair/'
Geometry_allPairs_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/Geometry_AllPairs/'
ID_PT_allPairs_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/ID_PT_AllPairs/'
MVis_allPairs_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MVis_AllPairs/'
GenPlots_dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/Gen/'
TauGeo_Dir='/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/TauGeo/'
checkAndMakeDir(Geometry_Dir)
checkAndMakeDir(MET_PreGeo_Dir)
checkAndMakeDir(ID_PT_PreGeo_Dir)
checkAndMakeDir(ID_PT_PostGeo_Dir)
checkAndMakeDir(MET_PostGeo_Dir)
checkAndMakeDir(Mvis_Dir)
checkAndMakeDir(Geometry_allPairs_Dir)
checkAndMakeDir(ID_PT_allPairs_Dir)
checkAndMakeDir(MVis_allPairs_Dir)
checkAndMakeDir(GenPlots_dir)
checkAndMakeDir(TauGeo_Dir)
JetPT= inFile.Get('simple/jetPt')

JetPT.SetLineColor(ROOT.kBlack)
JetPT.Draw()
c.SaveAs(MET_PostGeo_Dir+"JET_PT_GENERAL.png")
Make_Geo("eHad_geometry_gen", samp_mass, c, inFile, GenPlots_dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_gen", samp_mass, c, inFile, GenPlots_dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_gen", samp_mass, c, inFile, GenPlots_dir)
Make_IDPT("eHad_PT_gen", samp_mass, c, inFile, GenPlots_dir, False,True)
Make_IDPT("eHad_PT_postGeo_gen", samp_mass, c, inFile, GenPlots_dir, False, True)
Make_MVis("eHad_Mvis_gen", samp_mass, c, inFile, GenPlots_dir, True)
Make_TauGeo("eHad_METtoTau_JettoTau_PostGeo_gen", samp_mass,c, inFile, GenPlots_dir, True)
Make_TauGeo("eHad_METtoTau_JettoTau_gen", samp_mass,c, inFile, GenPlots_dir, True)

Make_Geo("eHad_geometry_NoID_MVA_m", samp_mass, c, inFile, Geometry_Dir)
Make_Geo("eHad_geometry_NoID_MVA", samp_mass, c, inFile, Geometry_Dir)
Make_Geo("eHad_geometry_NoID_MVA_f", samp_mass, c, inFile, Geometry_Dir)
Make_Geo("eHad_geometry_NoID_Standard_m", samp_mass, c, inFile, Geometry_Dir)
Make_Geo("eHad_geometry_NoID_Standard", samp_mass, c, inFile, Geometry_Dir)
Make_Geo("eHad_geometry_NoID_Standard_f", samp_mass, c, inFile, Geometry_Dir)

Make_Geo("eHad_geometry_allPairs_NoID_MVA_m", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_Geo("eHad_geometry_allPairs_NoID_MVA", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_Geo("eHad_geometry_allPairs_NoID_MVA_f", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_Geo("eHad_geometry_allPairs_NoID_Standard_m", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_Geo("eHad_geometry_allPairs_NoID_Standard", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_Geo("eHad_geometry_allPairs_NoID_Standard_f", samp_mass, c, inFile, Geometry_allPairs_Dir)
Make_TauGeo("eHad_METtoTau_JettoTau_PostGeo_NoID_MVA", samp_mass,c, inFile, TauGeo_Dir, False)
Make_TauGeo("eHad_METtoTau_JettoTau_NoID_MVA", samp_mass,c, inFile, TauGeo_Dir, False)

Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_MVA_m", samp_mass, c, inFile, MET_PreGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_MVA", samp_mass, c, inFile, MET_PreGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_MVA_f", samp_mass, c, inFile, MET_PreGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_Standard_m", samp_mass, c, inFile, MET_PreGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_Standard", samp_mass, c, inFile, MET_PreGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_NoID_Standard_f", samp_mass, c, inFile, MET_PreGeo_Dir)

Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_MVA_m", samp_mass, c, inFile, MET_PostGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_MVA", samp_mass, c, inFile, MET_PostGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_MVA_f", samp_mass, c, inFile, MET_PostGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_Standard_m", samp_mass, c, inFile, MET_PostGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_Standard", samp_mass, c, inFile, MET_PostGeo_Dir)
Make_MET_Jet("eHad_MET_VS_JdPhiM_postGeo_NoID_Standard_f", samp_mass, c, inFile, MET_PostGeo_Dir)

Make_MVis("eHad_Mvis_NoID_MVA", samp_mass, c, inFile, Mvis_Dir, False)
Make_MVis("eHad_Mvis_NoID_Standard", samp_mass, c, inFile, Mvis_Dir, False)
Make_MVis("eHad_Mvis_allPairs_NoID_MVA", samp_mass, c, inFile, MVis_allPairs_Dir, False)
Make_MVis("eHad_Mvis_allPairs_NoID_Standard", samp_mass, c, inFile, MVis_allPairs_Dir, False)
Make_IDPT("eHad_ID_PT_NoID_MVA", samp_mass, c, inFile, ID_PT_PreGeo_Dir, True, False)
Make_IDPT("eHad_ID_PT_NoID_Standard", samp_mass, c, inFile, ID_PT_PreGeo_Dir, False, False)
Make_IDPT("eHad_ID_PT_postGeo_NoID_MVA", samp_mass, c, inFile, ID_PT_PostGeo_Dir,True, False)
Make_IDPT("eHad_ID_PT_postGeo_NoID_Standard", samp_mass, c, inFile, ID_PT_PostGeo_Dir, False, False)
Make_IDPT("eHad_ID_PT_allPairs_NoID_MVA", samp_mass, c, inFile, ID_PT_allPairs_Dir,True, False)
Make_IDPT("eHad_ID_PT_allPairs_NoID_Standard", samp_mass, c, inFile, ID_PT_allPairs_Dir, False, False)

##############Geometry histos################



checkAndMakeDir('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/PT_PreGeo/')
NoID_Pt_MVA_m= inFile.Get('simple/eHad_ID_PT_NoID_MVA_m').ProjectionY("NoID_Pt_MVA_m")
NoID_Pt_MVA_m.SetTitle("PT (EHAD,MVA,Matched,NoGeo)("+samp_mass+")")
NoID_Pt_MVA_m.SetLineColor(ROOT.kBlack)
NoID_Pt_MVA_m.Draw()
Loose_Pt_MVA_m= inFile.Get('simple/eHad_ID_PT_Loose_MVA_m').ProjectionY("Loose_Pt_MVA_m")
Loose_Pt_MVA_m.SetLineColor(ROOT.kRed)
Loose_Pt_MVA_m.Draw("SAME")
Medium_Pt_MVA_m= inFile.Get('simple/eHad_ID_PT_Medium_MVA_m').ProjectionY("Medium_Pt_MVA_m")
Medium_Pt_MVA_m.SetLineColor(ROOT.kCyan)
Medium_Pt_MVA_m.Draw("SAME")
Tight_Pt_MVA_m= inFile.Get('simple/eHad_ID_PT_Tight_MVA_m').ProjectionY("Tight_Pt_MVA_m")
Tight_Pt_MVA_m.SetLineColor(ROOT.kGreen)
Tight_Pt_MVA_m.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_MVA_m,"ID>0","L")
leg.AddEntry(Loose_Pt_MVA_m,"ID>2","L")
leg.AddEntry(Medium_Pt_MVA_m,"ID>4","L")
leg.AddEntry(Tight_Pt_MVA_m,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA_m.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA_Log_m.png')
ROOT.gPad.SetLogy(0)
c.Clear()

NoID_Pt_MVA= inFile.Get('simple/eHad_ID_PT_NoID_MVA').ProjectionY("NoID_Pt_MVA")
NoID_Pt_MVA.SetTitle("PT (EHAD,MVA,Unmatched,NoGeo)("+samp_mass+")")
NoID_Pt_MVA.SetLineColor(ROOT.kBlack)
NoID_Pt_MVA.Draw()
Loose_Pt_MVA= inFile.Get('simple/eHad_ID_PT_Loose_MVA').ProjectionY("Loose_Pt_MVA")
Loose_Pt_MVA.SetLineColor(ROOT.kRed)
Loose_Pt_MVA.Draw("SAME")
Medium_Pt_MVA= inFile.Get('simple/eHad_ID_PT_Medium_MVA').ProjectionY("Medium_Pt_MVA")
Medium_Pt_MVA.SetLineColor(ROOT.kCyan)
Medium_Pt_MVA.Draw("SAME")
Tight_Pt_MVA= inFile.Get('simple/eHad_ID_PT_Tight_MVA').ProjectionY("Tight_Pt_MVA")
Tight_Pt_MVA.SetLineColor(ROOT.kGreen)
Tight_Pt_MVA.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_MVA,"ID>0","L")
leg.AddEntry(Loose_Pt_MVA,"ID>2","L")
leg.AddEntry(Medium_Pt_MVA,"ID>4","L")
leg.AddEntry(Tight_Pt_MVA,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA_Log.png')
ROOT.gPad.SetLogy(0)

c.Clear()


NoID_Pt_MVA_f= inFile.Get('simple/eHad_ID_PT_NoID_MVA_f').ProjectionY("NoID_Pt_MVA_f")
NoID_Pt_MVA_f.SetTitle("PT (EHAD,MVA,Fake,NoGeo) ("+samp_mass+")")
NoID_Pt_MVA_f.SetLineColor(ROOT.kBlack)
NoID_Pt_MVA_f.Draw()
Loose_Pt_MVA_f= inFile.Get('simple/eHad_ID_PT_Loose_MVA_f').ProjectionY("Loose_Pt_MVA_f")
Loose_Pt_MVA_f.SetLineColor(ROOT.kRed)
Loose_Pt_MVA_f.Draw("SAME")
Medium_Pt_MVA_f= inFile.Get('simple/eHad_ID_PT_Medium_MVA_f').ProjectionY("Medium_Pt_MVA_f")
Medium_Pt_MVA_f.SetLineColor(ROOT.kCyan)
Medium_Pt_MVA_f.Draw("SAME")
Tight_Pt_MVA_f= inFile.Get('simple/eHad_ID_PT_Tight_MVA_f').ProjectionY("Tight_Pt_MVA_f")
Tight_Pt_MVA_f.SetLineColor(ROOT.kGreen)
Tight_Pt_MVA_f.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_MVA_f,"ID>0","L")
leg.AddEntry(Loose_Pt_MVA_f,"ID>2","L")
leg.AddEntry(Medium_Pt_MVA_f,"ID>4","L")
leg.AddEntry(Tight_Pt_MVA_f,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA_f.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_MVA_Logf.png')
ROOT.gPad.SetLogy(0)

c.Clear()

NoID_Pt_Standard_m= inFile.Get('simple/eHad_ID_PT_NoID_Standard_m').ProjectionY("NoID_Pt_Standard_m")
NoID_Pt_Standard_m.SetTitle("PT (EHAD,Standard,Matched,NoGeo)("+samp_mass+")")
NoID_Pt_Standard_m.SetLineColor(ROOT.kBlack)
NoID_Pt_Standard_m.Draw()
Loose_Pt_Standard_m= inFile.Get('simple/eHad_ID_PT_Loose_Standard_m').ProjectionY("Loose_Pt_Standard_m")
Loose_Pt_Standard_m.SetLineColor(ROOT.kRed)
Loose_Pt_Standard_m.Draw("SAME")
Medium_Pt_Standard_m= inFile.Get('simple/eHad_ID_PT_Medium_Standard_m').ProjectionY("Medium_Pt_Standard_m")
Medium_Pt_Standard_m.SetLineColor(ROOT.kCyan)
Medium_Pt_Standard_m.Draw("SAME")
Tight_Pt_Standard_m= inFile.Get('simple/eHad_ID_PT_Tight_Standard_m').ProjectionY("Tight_Pt_Standard_m")
Tight_Pt_Standard_m.SetLineColor(ROOT.kGreen)
Tight_Pt_Standard_m.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_Standard_m,"NoID","L")
leg.AddEntry(Loose_Pt_Standard_m,"Loose","L")
leg.AddEntry(Medium_Pt_Standard_m,"Medium","L")
leg.AddEntry(Tight_Pt_Standard_m,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard_m.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard_Log_m.png')
ROOT.gPad.SetLogy(0)
c.Clear()

NoID_Pt_Standard= inFile.Get('simple/eHad_ID_PT_NoID_Standard').ProjectionY("NoID_Pt_Standard")
NoID_Pt_Standard.SetTitle("PT (EHAD,Standard,Unmatched,NoGeo)("+samp_mass+")")
NoID_Pt_Standard.SetLineColor(ROOT.kBlack)
NoID_Pt_Standard.Draw()
Loose_Pt_Standard= inFile.Get('simple/eHad_ID_PT_Loose_Standard').ProjectionY("Loose_Pt_Standard")
Loose_Pt_Standard.SetLineColor(ROOT.kRed)
Loose_Pt_Standard.Draw("SAME")
Medium_Pt_Standard= inFile.Get('simple/eHad_ID_PT_Medium_Standard').ProjectionY("Medium_Pt_Standard")
Medium_Pt_Standard.SetLineColor(ROOT.kCyan)
Medium_Pt_Standard.Draw("SAME")
Tight_Pt_Standard= inFile.Get('simple/eHad_ID_PT_Tight_Standard').ProjectionY("Tight_Pt_Standard")
Tight_Pt_Standard.SetLineColor(ROOT.kGreen)
Tight_Pt_Standard.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_Standard,"NoID","L")
leg.AddEntry(Loose_Pt_Standard,"Loose","L")
leg.AddEntry(Medium_Pt_Standard,"Medium","L")
leg.AddEntry(Tight_Pt_Standard,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard_Log.png')
ROOT.gPad.SetLogy(0)
c.Clear()

NoID_Pt_Standard_f= inFile.Get('simple/eHad_ID_PT_NoID_Standard_f').ProjectionY("NoID_Pt_Standard_f")
NoID_Pt_Standard_f.SetTitle("PT (EHAD,Standard,Fake,NoGeo) ("+samp_mass+")")
NoID_Pt_Standard_f.SetLineColor(ROOT.kBlack)
NoID_Pt_Standard_f.Draw()
Loose_Pt_Standard_f= inFile.Get('simple/eHad_ID_PT_Loose_Standard_f').ProjectionY("Loose_Pt_Standard_f")
Loose_Pt_Standard_f.SetLineColor(ROOT.kRed)
Loose_Pt_Standard_f.Draw("SAME")
Medium_Pt_Standard_f= inFile.Get('simple/eHad_ID_PT_Medium_Standard_f').ProjectionY("Medium_Pt_Standard_f")
Medium_Pt_Standard_f.SetLineColor(ROOT.kCyan)
Medium_Pt_Standard_f.Draw("SAME")
Tight_Pt_Standard_f= inFile.Get('simple/eHad_ID_PT_Tight_Standard_f').ProjectionY("Tight_Pt_Standard_f")
Tight_Pt_Standard_f.SetLineColor(ROOT.kGreen)
Tight_Pt_Standard_f.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_Standard_f,"NoID","L")
leg.AddEntry(Loose_Pt_Standard_f,"Loose","L")
leg.AddEntry(Medium_Pt_Standard_f,"Medium","L")
leg.AddEntry(Tight_Pt_Standard_f,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard_f.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_PreGeo/PT_Standard_Log_f.png')
ROOT.gPad.SetLogy(0)
c.Clear()

checkAndMakeDir('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/PT_postGeo/')
NoID_Pt_postGeo_MVA_m= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_MVA_m').ProjectionY("NoID_Pt_postGeo_MVA_m")
NoID_Pt_postGeo_MVA_m.SetTitle("PT_postGeo (EHAD,MVA,Matched,GeoCut)("+samp_mass+")")
NoID_Pt_postGeo_MVA_m.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_MVA_m.Draw()
Loose_Pt_postGeo_MVA_m= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_MVA_m').ProjectionY("Loose_Pt_postGeo_MVA_m")
Loose_Pt_postGeo_MVA_m.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_MVA_m.Draw("SAME")
Medium_Pt_postGeo_MVA_m= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_MVA_m').ProjectionY("Medium_Pt_postGeo_MVA_m")
Medium_Pt_postGeo_MVA_m.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_MVA_m.Draw("SAME")
Tight_Pt_postGeo_MVA_m= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_MVA_m').ProjectionY("Tight_Pt_postGeo_MVA_m")
Tight_Pt_postGeo_MVA_m.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_MVA_m.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_MVA_m,"ID>0","L")
leg.AddEntry(Loose_Pt_postGeo_MVA_m,"ID>2","L")
leg.AddEntry(Medium_Pt_postGeo_MVA_m,"ID>4","L")
leg.AddEntry(Tight_Pt_postGeo_MVA_m,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_MVA_m.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_MVA_LOG_m.png')
ROOT.gPad.SetLogy(0)
c.Clear()

NoID_Pt_postGeo_MVA= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_MVA').ProjectionY("NoID_Pt_postGeo_MVA")
NoID_Pt_postGeo_MVA.SetTitle("PT_postGeo (EHAD,MVA,Unmatched,GeoCut)("+samp_mass+")")
NoID_Pt_postGeo_MVA.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_MVA.Draw()
Loose_Pt_postGeo_MVA= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_MVA').ProjectionY("Loose_Pt_postGeo_MVA")
Loose_Pt_postGeo_MVA.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_MVA.Draw("SAME")
Medium_Pt_postGeo_MVA= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_MVA').ProjectionY("Medium_Pt_postGeo_MVA")
Medium_Pt_postGeo_MVA.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_MVA.Draw("SAME")
Tight_Pt_postGeo_MVA= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_MVA').ProjectionY("Tight_Pt_postGeo_MVA")
Tight_Pt_postGeo_MVA.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_MVA.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_MVA,"ID>0","L")
leg.AddEntry(Loose_Pt_postGeo_MVA,"ID>2","L")
leg.AddEntry(Medium_Pt_postGeo_MVA,"ID>4","L")
leg.AddEntry(Tight_Pt_postGeo_MVA,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_MVA.png')
ROOT.gPad.SetLogy()

c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_LOG_MVA.png')
ROOT.gPad.SetLogy(0)

NoID_Pt_postGeo_MVA_f= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_MVA_f').ProjectionY("NoID_Pt_postGeo_MVA_f")
NoID_Pt_postGeo_MVA_f.SetTitle("PT_postGeo (EHAD,MVA,Fake,GeoCut) ("+samp_mass+")")
NoID_Pt_postGeo_MVA_f.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_MVA_f.Draw()
Loose_Pt_postGeo_MVA_f= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_MVA_f').ProjectionY("Loose_Pt_postGeo_MVA_f")
Loose_Pt_postGeo_MVA_f.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_MVA_f.Draw("SAME")
Medium_Pt_postGeo_MVA_f= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_MVA_f').ProjectionY("Medium_Pt_postGeo_MVA_f")
Medium_Pt_postGeo_MVA_f.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_MVA_f.Draw("SAME")
Tight_Pt_postGeo_MVA_f= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_MVA_f').ProjectionY("Tight_Pt_postGeo_MVA_f")
Tight_Pt_postGeo_MVA_f.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_MVA_f.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_MVA_f,"ID>0","L")
leg.AddEntry(Loose_Pt_postGeo_MVA_f,"ID>2","L")
leg.AddEntry(Medium_Pt_postGeo_MVA_f,"ID>4","L")
leg.AddEntry(Tight_Pt_postGeo_MVA_f,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_MVA_f.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_MVA_LOG_f.png')
ROOT.gPad.SetLogy(0)

NoID_Pt_postGeo_Standard_m= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_Standard_m').ProjectionY("NoID_Pt_postGeo_Standard_m")
NoID_Pt_postGeo_Standard_m.SetTitle("PT_postGeo (EHAD,Standard,Matched,GeoCut)("+samp_mass+")")
NoID_Pt_postGeo_Standard_m.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_Standard_m.Draw()
Loose_Pt_postGeo_Standard_m= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_Standard_m').ProjectionY("Loose_Pt_postGeo_Standard_m")
Loose_Pt_postGeo_Standard_m.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_Standard_m.Draw("SAME")
Medium_Pt_postGeo_Standard_m= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_Standard_m').ProjectionY("Medium_Pt_postGeo_Standard_m")
Medium_Pt_postGeo_Standard_m.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_Standard_m.Draw("SAME")
Tight_Pt_postGeo_Standard_m= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_Standard_m').ProjectionY("Tight_Pt_postGeo_Standard_m")
Tight_Pt_postGeo_Standard_m.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_Standard_m.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_Standard_m,"NoID","L")
leg.AddEntry(Loose_Pt_postGeo_Standard_m,"Loose","L")
leg.AddEntry(Medium_Pt_postGeo_Standard_m,"Medium","L")
leg.AddEntry(Tight_Pt_postGeo_Standard_m,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard_m.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard_LOG_m.png')
ROOT.gPad.SetLogy(0)

NoID_Pt_postGeo_Standard= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_Standard').ProjectionY("NoID_Pt_postGeo_Standard")
NoID_Pt_postGeo_Standard.SetTitle("PT_postGeo (EHAD,Standard,Unmatched,GeoCut)("+samp_mass+")")
NoID_Pt_postGeo_Standard.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_Standard.Draw()
Loose_Pt_postGeo_Standard= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_Standard').ProjectionY("Loose_Pt_postGeo_Standard")
Loose_Pt_postGeo_Standard.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_Standard.Draw("SAME")
Medium_Pt_postGeo_Standard= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_Standard').ProjectionY("Medium_Pt_postGeo_Standard")
Medium_Pt_postGeo_Standard.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_Standard.Draw("SAME")
Tight_Pt_postGeo_Standard= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_Standard').ProjectionY("Tight_Pt_postGeo_Standard")
Tight_Pt_postGeo_Standard.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_Standard.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_Standard,"NoID","L")
leg.AddEntry(Loose_Pt_postGeo_Standard,"Loose","L")
leg.AddEntry(Medium_Pt_postGeo_Standard,"Medium","L")
leg.AddEntry(Tight_Pt_postGeo_Standard,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard_LOG.png')
ROOT.gPad.SetLogy(0)


NoID_Pt_postGeo_Standard_f= inFile.Get('simple/eHad_ID_PT_postGeo_NoID_Standard_f').ProjectionY("NoID_Pt_postGeo_Standard_f")
NoID_Pt_postGeo_Standard_f.SetTitle("PT_postGeo (EHAD,Standard,Fake,GeoCut) ("+samp_mass+")")
NoID_Pt_postGeo_Standard_f.SetLineColor(ROOT.kBlack)
NoID_Pt_postGeo_Standard_f.Draw()
Loose_Pt_postGeo_Standard_f= inFile.Get('simple/eHad_ID_PT_postGeo_Loose_Standard_f').ProjectionY("Loose_Pt_postGeo_Standard_f")
Loose_Pt_postGeo_Standard_f.SetLineColor(ROOT.kRed)
Loose_Pt_postGeo_Standard_f.Draw("SAME")
Medium_Pt_postGeo_Standard_f= inFile.Get('simple/eHad_ID_PT_postGeo_Medium_Standard_f').ProjectionY("Medium_Pt_postGeo_Standard_f")
Medium_Pt_postGeo_Standard_f.SetLineColor(ROOT.kCyan)
Medium_Pt_postGeo_Standard_f.Draw("SAME")
Tight_Pt_postGeo_Standard_f= inFile.Get('simple/eHad_ID_PT_postGeo_Tight_Standard_f').ProjectionY("Tight_Pt_postGeo_Standard_f")
Tight_Pt_postGeo_Standard_f.SetLineColor(ROOT.kGreen)
Tight_Pt_postGeo_Standard_f.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_Pt_postGeo_Standard_f,"NoID","L")
leg.AddEntry(Loose_Pt_postGeo_Standard_f,"Loose","L")
leg.AddEntry(Medium_Pt_postGeo_Standard_f,"Medium","L")
leg.AddEntry(Tight_Pt_postGeo_Standard_f,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard_f.png')
ROOT.gPad.SetLogy()
c.SaveAs(outfolder+ '/PT_postGeo/PT_postGeo_Standard_LOG_f.png')
ROOT.gPad.SetLogy(0)

c.Clear()



checkAndMakeDir('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/Counting/')
inFile.cd("simple")
for key in inFile.GetListOfKeys():
    h = key.ReadObj()
    if h.ClassName() == 'TH1F':
        h.Draw()
        c.SaveAs(outfolder+"/Counting/"+h.GetName()+".png")
checkAndMakeDir('/uscms_data/d3/nbower/FSU/LowPtIDStudies/CMSSW_10_6_12/src/myLowPtGsfElectronsAnalyzer/myLowPtGsfElectronsAnalyzer/graphs/'+samp_mass+"_"+label+'/MatchedOverUnMatched/')

NoID_pt_MVA_uvm= ROOT.TH1F('NoID_pt_MVA_uvm', 'NMatchedEle/NUnmatchedEle PT (LowPTReco, Post Geo)',  30 , 0 , 400)
NoID_pt_MVA_uvm.SetLineColor(ROOT.kBlack)
Loose_pt_MVA_uvm= ROOT.TH1F('Loose_pt_MVA_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Loose_pt_MVA_uvm.SetLineColor(ROOT.kRed)
Medium_pt_MVA_uvm= ROOT.TH1F('Medium_pt_MVA_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Medium_pt_MVA_uvm.SetLineColor(ROOT.kCyan)
Tight_pt_MVA_uvm= ROOT.TH1F('Tight_pt_MVA_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Tight_pt_MVA_uvm.SetLineColor(ROOT.kGreen)

NoID_pt_Standard_uvm= ROOT.TH1F('NoID_pt_Standard_uvm', 'NMatchedEle/NUnmatchedEle PT (Standard,Post Geo)',  30 , 0 , 400)
NoID_pt_Standard_uvm.SetLineColor(ROOT.kBlack)
Loose_pt_Standard_uvm= ROOT.TH1F('Loose_pt_Standard_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Loose_pt_Standard_uvm.SetLineColor(ROOT.kRed)
Medium_pt_Standard_uvm= ROOT.TH1F('Medium_pt_Standard_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Medium_pt_Standard_uvm.SetLineColor(ROOT.kCyan)
Tight_pt_Standard_uvm= ROOT.TH1F('Tight_pt_Standard_uvm', 'Signal IntegralsTCPm10pt400',  30 , 0 , 400)
Tight_pt_Standard_uvm.SetLineColor(ROOT.kGreen)

for i in range(1, 30):
    if NoID_Pt_postGeo_MVA.GetBinContent(i)!=0:
        NoID_pt_MVA_uvm.SetBinContent(i,NoID_Pt_postGeo_MVA_m.GetBinContent(i)/NoID_Pt_postGeo_MVA.GetBinContent(i))
    else:
        NoID_pt_MVA_uvm.SetBinContent(i,0)
    if Loose_Pt_postGeo_MVA.GetBinContent(i)!=0:
        Loose_pt_MVA_uvm.SetBinContent(i,Loose_Pt_postGeo_MVA_m.GetBinContent(i)/Loose_Pt_postGeo_MVA.GetBinContent(i))
    else:
        Loose_pt_MVA_uvm.SetBinContent(i,0)
    if Medium_Pt_postGeo_MVA.GetBinContent(i)!=0:
        Medium_pt_MVA_uvm.SetBinContent(i,Medium_Pt_postGeo_MVA_m.GetBinContent(i)/Medium_Pt_postGeo_MVA.GetBinContent(i))
    else:
        Medium_pt_MVA_uvm.SetBinContent(i,0)
    if Tight_Pt_postGeo_MVA.GetBinContent(i)!=0:
        Tight_pt_MVA_uvm.SetBinContent(i,Tight_Pt_postGeo_MVA_m.GetBinContent(i)/Tight_Pt_postGeo_MVA.GetBinContent(i))
    else:
        Tight_pt_MVA_uvm.SetBinContent(i,0)

    if NoID_Pt_postGeo_Standard.GetBinContent(i)!=0:
        NoID_pt_Standard_uvm.SetBinContent(i,NoID_Pt_postGeo_Standard_m.GetBinContent(i)/NoID_Pt_postGeo_Standard.GetBinContent(i))
    else:
        NoID_pt_Standard_uvm.SetBinContent(i,0)
    if Loose_Pt_postGeo_Standard.GetBinContent(i)!=0:
        Loose_pt_Standard_uvm.SetBinContent(i,Loose_Pt_postGeo_Standard_m.GetBinContent(i)/Loose_Pt_postGeo_Standard.GetBinContent(i))
    else:
        Loose_pt_Standard_uvm.SetBinContent(i,0)
    if Medium_Pt_postGeo_Standard.GetBinContent(i)!=0:
        Medium_pt_Standard_uvm.SetBinContent(i,Medium_Pt_postGeo_Standard_m.GetBinContent(i)/Medium_Pt_postGeo_Standard.GetBinContent(i))
    else:
        Medium_pt_Standard_uvm.SetBinContent(i,0)
    if Tight_Pt_postGeo_Standard.GetBinContent(i)!=0:
        Tight_pt_Standard_uvm.SetBinContent(i,Tight_Pt_postGeo_Standard_m.GetBinContent(i)/Tight_Pt_postGeo_Standard.GetBinContent(i))
    else:
        Tight_pt_Standard_uvm.SetBinContent(i,0)
NoID_pt_MVA_uvm.SetMaximum(1.1)
NoID_pt_MVA_uvm.Draw()
Loose_pt_MVA_uvm.Draw("SAME")
Medium_pt_MVA_uvm.Draw("SAME")
Tight_pt_MVA_uvm.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_pt_MVA_uvm,"ID>0","L")
leg.AddEntry(Loose_pt_MVA_uvm,"ID>2","L")
leg.AddEntry(Medium_pt_MVA_uvm,"ID>4","L")
leg.AddEntry(Tight_pt_MVA_uvm,"ID>6","L")
leg.Draw()
c.SaveAs(outfolder+ '/MatchedOverUnMatched/PTuvm_MVA.png')
c.Clear()

NoID_pt_Standard_uvm.SetMaximum(1.1)

NoID_pt_Standard_uvm.Draw()
Loose_pt_Standard_uvm.Draw("SAME")
Medium_pt_Standard_uvm.Draw("SAME")
Tight_pt_Standard_uvm.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(NoID_pt_Standard_uvm,"NoID","L")
leg.AddEntry(Loose_pt_Standard_uvm,"Loose","L")
leg.AddEntry(Medium_pt_Standard_uvm,"Medium","L")
leg.AddEntry(Tight_pt_Standard_uvm,"Tight","L")
leg.Draw()
c.SaveAs(outfolder+ '/MatchedOverUnMatched/PTuvm_Standard.png')
c.Clear()
print "NoID MVA Integral Matched: "+ str(NoID_Pt_postGeo_MVA_m.Integral())+", NoID MVA Integral Unmatched: "+str(NoID_Pt_postGeo_MVA.Integral())+" \n"
print "Ratio: "+ str(NoID_Pt_postGeo_MVA_m.Integral()/NoID_Pt_postGeo_MVA.Integral())+" \n"
print "Loose MVA Integral Matched: "+ str(Loose_Pt_postGeo_MVA_m.Integral())+", Loose MVA Integral Unmatched: "+str(Loose_Pt_postGeo_MVA.Integral())+" \n"
print "Ratio: "+ str(Loose_Pt_postGeo_MVA_m.Integral()/Loose_Pt_postGeo_MVA.Integral())+" \n"
print "Medium MVA Integral Matched: "+ str(Medium_Pt_postGeo_MVA_m.Integral())+", Medium MVA Integral Unmatched: "+str(Medium_Pt_postGeo_MVA.Integral())+" \n"
print "Ratio: "+ str(Medium_Pt_postGeo_MVA_m.Integral()/Medium_Pt_postGeo_MVA.Integral())+" \n"
print "Tight MVA Integral Matched: "+ str(Tight_Pt_postGeo_MVA_m.Integral())+", Tigh MVA Integral Unmatched: "+str(Tight_Pt_postGeo_MVA.Integral())+" \n"
print "Ratio: "+ str(Tight_Pt_postGeo_MVA_m.Integral()/Tight_Pt_postGeo_MVA.Integral())+" \n"

print "NoID Standard Integral Matched: "+ str(NoID_Pt_postGeo_Standard_m.Integral())+", NoID Standard Integral Unmatched: "+str(NoID_Pt_postGeo_Standard.Integral())+" \n"
print "Ratio: "+ str(NoID_Pt_postGeo_Standard_m.Integral()/NoID_Pt_postGeo_Standard.Integral())+" \n"
print "Loose Standard Integral Matched: "+ str(Loose_Pt_postGeo_Standard_m.Integral())+", Loose Standard Integral Unmatched: "+str(Loose_Pt_postGeo_Standard.Integral())+" \n"
print "Ratio: "+ str(Loose_Pt_postGeo_Standard_m.Integral()/Loose_Pt_postGeo_Standard.Integral())+" \n"
print "Medium Standard Integral Matched: "+ str(Medium_Pt_postGeo_Standard_m.Integral())+", Medium Standard Integral Unmatched: "+str(Medium_Pt_postGeo_Standard.Integral())+" \n"
print "Ratio: "+ str(Medium_Pt_postGeo_Standard_m.Integral()/Medium_Pt_postGeo_Standard.Integral())+" \n"
print "Tight Standard Integral Matched: "+ str(Tight_Pt_postGeo_Standard_m.Integral())+", Tigh Standard Integral Unmatched: "+str(Tight_Pt_postGeo_Standard.Integral())+" \n"
print "Ratio: "+ str(Tight_Pt_postGeo_Standard_m.Integral()/Tight_Pt_postGeo_Standard.Integral())+" \n"

FakeRateMVA= ROOT.TH1F('FakeRateMVA', 'Post Geo Fake Rates',  4 , 0 , 4)
FakeRateMVA.SetLineColor(ROOT.kBlue)
FakeRateMVA.SetBinContent(1,NoID_Pt_postGeo_MVA_m.Integral()/NoID_Pt_postGeo_MVA.Integral())
FakeRateMVA.SetBinContent(2,Loose_Pt_postGeo_MVA_m.Integral()/Loose_Pt_postGeo_MVA.Integral())
FakeRateMVA.SetBinContent(3,Medium_Pt_postGeo_MVA_m.Integral()/Medium_Pt_postGeo_MVA.Integral())
FakeRateMVA.SetBinContent(4,Tight_Pt_postGeo_MVA_m.Integral()/Tight_Pt_postGeo_MVA.Integral())

FakeRateStandard= ROOT.TH1F('FakeRateStandard', 'Post Geo Fake Rates',  4 , 0 , 4)
FakeRateStandard.SetLineColor(ROOT.kRed)
FakeRateStandard.SetBinContent(1,NoID_Pt_postGeo_Standard_m.Integral()/NoID_Pt_postGeo_Standard.Integral())
FakeRateStandard.SetBinContent(2,Loose_Pt_postGeo_Standard_m.Integral()/Loose_Pt_postGeo_Standard.Integral())
FakeRateStandard.SetBinContent(3,Medium_Pt_postGeo_Standard_m.Integral()/Medium_Pt_postGeo_Standard.Integral())
FakeRateStandard.SetBinContent(4,Tight_Pt_postGeo_Standard_m.Integral()/Tight_Pt_postGeo_Standard.Integral())
FakeRateStandard.SetAxisRange(0,1,"Y")
FakeRateStandard.Draw()

FakeRateMVA.Draw("SAME")
leg = ROOT.TLegend(.73,.32,.97,.53)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)
leg.AddEntry(FakeRateMVA,"MVA","L")
leg.AddEntry(FakeRateStandard,"Standard","L")
leg.Draw()
c.SaveAs(outfolder+ '/MatchedOverUnMatched/OVERALL_Fakerate.png')
